<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'MARIA GAMESA 180G / 22 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'CRACKETS 135G / 20 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'CRACKETS 135G / 22 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'MARIA CUETARA 160G / 20 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'ORO CUETARA 200G / 20 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'PAN CUETARA 150G / 20 PAQUETES',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'PAN CREMA 151G / 20 PAQUETES',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'PAN CREMA 151G / 22 PAQUETES',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'MARIA AZUCARADAS 144G / 22 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'MARIANITAS CANELA 170G / 20 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'MARIANITAS NUEZ 170G / 20 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'MARIANITAS COCO 170G / 20 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'MARIA GAMESA 204G / 30 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'MEXICANAS CUETARA 135G / 20 PAQUETES',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'MARAVILLAS GAMESA 125G / 20 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'ANIMALITO CUETARA / 1 BOLSA 5KG',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'OVALADA CUETARA / 1 BOLSA 5KG',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'ANIMALITO PRIMA / 1 BOLSA 4.5KG',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'ANIMALITO PRIMA BOLSA 500G / 12 PAQUETES',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'OVALADA GAPGA / 1 BOLSA 5KG',
                'category_id' => 6,
                'measure_unit_id' => 14,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'ANIMALITO GAPGA / 1 BOLSA 5KG',
                'category_id' => 6,
                'measure_unit_id' => 14,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'MARIAS DORADAS 199G / 15 ROLLOS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'SURTIDO RICO 424G / 13 PAQUETES',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'POPULARES GAMESA 1KG / 6 BOLSAS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'BISCOCHITO GAMESA 150MG / 12 BOLSAS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'YOGURT LALA 220G / 1 PAQUETE DE 24 PZA',
                'category_id' => 1,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'LALA DESLACTOSADA 1 LITRO / 12 PZA',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'NUTRI LECHE 1 LITRO / 12 PZA',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'MEDIA CREMA LALA 250ML / 27 PZA',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'CLAVEL CARNATION 340ML / 48PZA',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'LECHERA NESTLE 284ML / 48PZA',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'LECEHRA SOBRE 209G / 20 SOBRES',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 12,
            ],
            [
                'name' => 'LECHERITA NESTLE 100G / 48PZA',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'NEGRO CAFÉ DOLCA 46G / 15PZA',
                'category_id' => 9,
                'measure_unit_id' => 26,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'NESCAFE DOLCA 170G / 15PZA',
                'category_id' => 9,
                'measure_unit_id' => 26,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'NESCAFE CLASICO 350G / 1 CHAROLA 6PZA',
                'category_id' => 9,
                'measure_unit_id' => 26,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'NESCAFE DOLCA DOY PAC 22G / 20 SOBRES',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 12,
            ],
            [
                'name' => 'NESCAFE DOLCA DOY PAC 28G / 24 SOBRES',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 12,
            ],
            [
                'name' => 'NESCAFE DOLCA STIC CAJA CON 9 EXHIBIDORES 10G / 16 SOBRES',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 12,
            ],
            [
                'name' => 'CAFÉ UNICO CAJA CON 10 EXHIBIDORES DE 14G / 20 SOBRES',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 12,
            ],
            [
                'name' => 'CAFÉ DAVID / 10 EXHIBIDORES DE 50 SOBRES',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 12,
            ],
            [
                'name' => 'ABSORSEC XJ ETAPA 6 / ',
                'category_id' => 13,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'ABSORSEC J ETAPA 5 / ',
                'category_id' => 13,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'ABSORSEC G ETAPA 4 / ',
                'category_id' => 13,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'ABSORSEC M ETAPA 3 / ',
                'category_id' => 13,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'PREMIER JUMBO 400HOJAS / 12 PAQUETES',
                'category_id' => 13,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'REGIO HIGIENICO RINDE 400HOJAS / 10 PAQUETES',
                'category_id' => 13,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'SERVILLETAS DELSEY 100HOJAS / 9 PAQUETES',
                'category_id' => 13,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'SUAVEL 200HOJAS / 12 PAQUETES DE 4 ROLLOS',
                'category_id' => 13,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'SUAVEL 200 HOJAS / 48 ROLLOS',
                'category_id' => 13,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'RANCHO ESCONDIDO 750ML / CAJA CON 12 BOTELLAS',
                'category_id' => 19,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'COMPADRE 750ML / CAJA CON 12 BOTELLAS',
                'category_id' => 19,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'CHARRITO 250ML / CAJA CON 24 BOTELLAS',
                'category_id' => 19,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'ELECTROLIT: COCO, FRESA, UVA, MORA, FRESA-KIWI 625ML / CAJA CON 12 BOTELLAS',
                'category_id' => 8,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'COCA-COLA 600ML / PAQUETE 24 PZA',
                'category_id' => 8,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'COCA-COLA 1.35LT / PAQUETE 12 PZA',
                'category_id' => 8,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'COCA-COLA 3LT / PAQUETE 8PZA',
                'category_id' => 8,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'VOLT AZUL GUARANA 473ML / PAQUETE 15PZA',
                'category_id' => 8,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'VOLT CELESTE MORA AZUL 473ML / PAQUETE 15 PZA',
                'category_id' => 8,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'POWERADE AZUL 1LT / PAQUETE 6PZA',
                'category_id' => 8,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'JUGO DEL VALLE NARANJA 1LT / PAQUETE 8PZA',
                'category_id' => 8,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'MODELO ESPECIAL 355ML / CHAROLA CON 4 SIX',
                'category_id' => 19,
                'measure_unit_id' => 26,
                'retail_measure_unit_id' => 32,
            ],
            [
                'name' => 'JAROCHITA 155G / 50PZA',
                'category_id' => 3,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'KOLA LOCA / 20 EXHIBIDORES DE 10 PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'LAPICERO BIC AZUL / 100 CAJAS DE 12 PZA',
                'category_id' => 22,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'LAPICERO BIC NEGRO / 101 CAJAS DE 12 PZA',
                'category_id' => 22,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'HORCHATA FLOR DE MARIA 230ML / 24 BOTELLAS',
                'category_id' => 23,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'HORCHATA FLOR DE MARIA 500ML / 12 BOTELLAS',
                'category_id' => 23,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'HORCHATA FLOR DE MARIA 1LT / 12 BOTELLAS',
                'category_id' => 23,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'HORCHATA FLOR DE MARIA 3.780LT / 4 BOTELLAS',
                'category_id' => 23,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'COLGATE TRIPLE ACCION 150ML / CHAROLA CON 9 PAQUETES',
                'category_id' => 12,
                'measure_unit_id' => 26,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'COLGATE TRIPLE ACCION 140ML / CAJA CON 72PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'COLGATE TRIPLE ACCION 75ML / 5 PAQUETES DE 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'COLGATE TRIPLE ACCION EXTRA BLANCURA 50ML / 12 PAQUETES DE 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'COLGATE MAXIMA PROTECCION ANTICARIES 50ML / 12 PAQUETES DE 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'COLGATE MAXIMA PROTECCION ANTICARIES 75ML / 12 PAQUETES DE 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'CEPILLO COLGATE PREMIER CLEAN / CAJA CON 8 EXHIBIDORES DE 6PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'CEPILLO COLGATE TIRA / CAJA CON 24 TIRAS DE 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 28,
            ],
            [
                'name' => 'CEPILLO MAXIPLUS / CAJA CON 40 TIRAS CON 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 28,
            ],
            [
                'name' => 'AXION LIMON LIQUIDO 900ML / CAJA 12PZA',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'AXION LIMON LIQUIDO 400ML / 15PZA',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'BLANCA NIEVES 250G / 40PZA',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'BLANCA NIEVES 500G / 20PZA',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'BLANCA NIEVES 1KG / 10PZA',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'CLORO CLARASOL 1LT / 12 BOTELLAS',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'CLORO CLARASOL 500ML / 20 BOTELLAS',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'COTONETTE QUIRMEX / CAJA CON 40 TIRAS CON 20 SOBRES',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 28,
            ],
            [
                'name' => 'JABON FOCA 250G / 40 BOLSAS',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'JABON FOCA 500G / 20 BOLSAS',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'JABON FOCA 1KG / 10 BOLSAS',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'JABON ZOTE 400MG / 25PZA',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'JABON ZOTE 200MG / 50PZA',
                'category_id' => 15,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'PALETA DEDO  / CAJA 24 BOLSAS DE 30 PZ',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'BOMBOM MALVAVISCO 1KG / CAJA DE 8 BOLSAS ',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'VUALA CAJETA / 6PZA',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'VUALA CHOCOLATE / 6PZA',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'VUALA VAINILLA / 6PZA',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'NISSIN NEGRA CAMARON 64G / PAQUETE CON 12 VASOS',
                'category_id' => 24,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 29,
            ],
            [
                'name' => 'NISSIN VERDE CAMARON 64G / PAQUETE CON 12 VASOS',
                'category_id' => 24,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 29,
            ],
            [
                'name' => 'MARUCHAN LIMON-CAMARON-HABANERO 64G / PAQUETE CON 12 VASOS',
                'category_id' => 24,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 29,
            ],
            [
                'name' => 'MARUCHAN RAMEN 85G / PAQUETE CON 24 BOLSAS',
                'category_id' => 24,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'MARUCHAN BOWL 94.3G / PAQUETE CON 6 TAZONES',
                'category_id' => 24,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 30,
            ],
            [
                'name' => 'SPAGUETTI 200G / CAJA CON 20 BOLSAS',
                'category_id' => 24,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'FIDEO GRUESA 180G / CAJA CON 20 BOLSAS',
                'category_id' => 24,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'HABANERO ANITA 120ML / CAJA CON 5 PAQUETES DE 4PZA',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CATSUP CLEMENETE 340G / CAJA CON 24PZA',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'CATSUP CLEMENETE 220G / CAJA CON 24PZA',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'SALSA CASERA LA COSTEÑA 220G / 24 PZA',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'SALSA CASERA HERDEZ 220G / 24PZA',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'SALSA SOYA REGIA 80ML / 48PZA',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'SALSA VALENTINA ROJA 370ML / 24 BOTELLAS',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'ARROZ SCHETTINO 250G / PAQUETE CON 40PZA',
                'category_id' => 2,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'ARROZ SCHETTINO 500G / PAQUETE CON 20PZA',
                'category_id' => 2,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'ARROZ SCHETTINO 900G / PAQUETE CON 10PZA',
                'category_id' => 2,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'CACAHUATE ENCHILADO / 10 KILOS',
                'category_id' => 7,
                'measure_unit_id' => 3,
                'retail_measure_unit_id' => 20,
            ],
            [
                'name' => 'FRIJOL REFRITO ISADORA 430G / PAQUETE CON 6  BOLSAS',
                'category_id' => 3,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'FRIJOL LA SIERRA 430G / 24 BOLSAS',
                'category_id' => 3,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'AVENA 3 MINUTOS 380G / CAJA CON 36 BOLSAS',
                'category_id' => 2,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'AZUCAR ZUCARMEX / 25KG',
                'category_id' => 9,
                'measure_unit_id' => 3,
                'retail_measure_unit_id' => 20,
            ],
            [
                'name' => 'HOT CAKES PRONTO 500G / 3 PZA',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'HARINA DE ARROZ 250G / 18 PAQUETES',
                'category_id' => 2,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'MAIZENA 95G / 10PZA',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'MASECA BLANCA 1KG / 10 PAQUETES',
                'category_id' => 2,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'NUTRIOLI 400ML / 12PZA',
                'category_id' => 4,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'NUTRIOLI 800ML / 12PZA',
                'category_id' => 4,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'CIGARROS GOLD SEAL ROJO / CAJA 50 PAQUETES DE 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CIGARROS GOLD SEAL VERDE / CAJA 50 PAQUETES DE 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CIGARRO GOLD SEAL 2 CLIP NEGRO / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'THIS: SANDIA, MANGO, UVA / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'LG PREMIUN VERDE Y ROJO / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'THRILL MANGO / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'BENSON MENTOLADO / PAQUETE 10PZA',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'MALBORO GARDEN FUSION / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'MALBORO ICE XPRESS / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'MALBORO KRETEK MINT / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'MALBORO ROJO CIEN / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'MALBORO ROJO ORIGINAL / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'MALBORO RUBY / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'MALBORO SUMMENR FUSION / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'MALBORO VELVET / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'PALL MALL ALASKA / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'PALL MALL PEPINO / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'PALL MALL TOKYO / 10 CAJETILLAS',
                'category_id' => 18,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'MAYONESA McCORMICK #4 105G / 24PZA',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'MAYONESA McCORMICK #8 190G / 24PZA',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'MAYONESA McCORMICK #9 228G / 24PZA',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'MAYONESA McCORMICK #16 390G / 12PZA',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'MAYONESA McCORMICK #16 468G / 12PZA',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'MAYONESA McCORMICK 3.4KG / 6PZA',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'MERMELADA FRESA 165G / 12PZA',
                'category_id' => 3,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'PURE DE TOMATE LA COSTEÑA 210G / 24PZA',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'SARDINA YAVOROG 425G / 24PZA',
                'category_id' => 4,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'VINAGRE CLEMENTE 500ML / 24 BOTELLAS',
                'category_id' => 4,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'VINAGRE CLEMENTE 1LT / 12 BOTELLAS',
                'category_id' => 4,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'KNORSUIZA 21G / CAJA CON 12 ESTUCHES',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 31,
            ],
            [
                'name' => 'KNORTOMATE 21G / CAJA CON 12 ESTUCHES',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 31,
            ],
            [
                'name' => 'RIKOMATE 11G / CAJA CON 8 EXHIBIDORES',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'RIKOPOLLO 11G / CAJA CON 8 EXHIBIDORES',
                'category_id' => 10,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'FOCO CHILLODA 60-75 W / CAJA CON 10 PAQUETES 10PZ',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'FOCO AHORRADOR LIMON 25W / CAJA CON 50 PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'FOCO AHORRADOR MAXI LUZ / CAJA CON 10 PAQUETES',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'PALMOLIVE NEUTRO 100G / CAJA CON 12 PAQUETES DE 8 PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'PALMOLIVE NATURALS VERDE 120G / CAJA CON 8 PAQUETES DE 8PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CERILLO MAYA / 10 PAQUETES DE 10 CAJETILLAS',
                'category_id' => 17,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CERILLO FLAMA / CAJA CON 50 PAQUETES CON 5 CAJETILLAS',
                'category_id' => 17,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CHAO MEIN 180G / CAJA CON 48PZA',
                'category_id' => 24,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'HUEVO SAN JUAN 18 KG / 12 CONOS DE 30 HUEVOS',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 27,
            ],
            [
                'name' => 'HUEVO SAN JUAN 19 KG / 12 CONOS DE 30 HUEVOS',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 27,
            ],
            [
                'name' => 'HUEVO SAN JUAN 20 KG / 12 CONOS DE 30 HUEVOS',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 27,
            ],
            [
                'name' => 'HUEVO SAN JUAN 21 KG / 12 CONOS DE 30 HUEVOS',
                'category_id' => 1,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 27,
            ],
            [
                'name' => 'SABA NOCTURNA BUENAS NOCHES / CAJA CON 6 PAQUETES DE 8 TOALLAS',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CHICLE BUBALO TUTI-FRUIT MORA AZUL, PLATANO, MENTA, HIERBABUENA, PICA PIÑA, FRESA / CAJA CON 32 EXHIBIDORES CON 47 PZA',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'CHICLE MAX AIR / CAJA CON 32 EXHIBIDORES CON 75 PAQUETES',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'CHICLE CLORENTS / CAJA CON 32 EXHIBIDORES DE 60 CAJETILLAS',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'HALLS: CEREZA, MENTA, BOOST, MORA AZUL, MIEL, NEGRO / CAJA CON 30 PAQUETES CON 12 PZA',
                'category_id' => 6,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'PALOMITA EXTRA MANTEQUILLA 87G / 16 SOBRES',
                'category_id' => 7,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 12,
            ],
            [
                'name' => 'CHOCOLATE ABUELITA / CAJA CON 24 PAQUETES DE 6 PZA',
                'category_id' => 23,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CHOCOLATE ABUELITA  / CAJA CON 24 PAQUETES DE 7PZA',
                'category_id' => 23,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CHOCOMILK SOBRE 160G / CAJA CON 40 SOBRES',
                'category_id' => 23,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 12,
            ],
            [
                'name' => 'ENCENDEDOR WONDER LITE / CAJA CON 20 EXHIBIDORES CON 25PZA',
                'category_id' => 17,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'ENCENDEDOR BIC MINI / 15PZA',
                'category_id' => 17,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'ENCENDEDOR DECORADO / CAJA CON 50 TIRAS DE 24 PZA',
                'category_id' => 17,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 28,
            ],
            [
                'name' => 'ENCENDEDOR MINI TOKAI / CAJA CON 55 TIRAS DE 20PZA',
                'category_id' => 17,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 28,
            ],
            [
                'name' => 'ENCENDEDOR TOCAYO / CAJA CON 50 EXHIBIDORES DE 50 PZA',
                'category_id' => 17,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'CERILLO FLAMA / CAJA CON 50 PAQUETES DE 5PZA',
                'category_id' => 17,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CERILLO JAGUAR / CAJA CON 10 PAQUETES DE 50PZA',
                'category_id' => 17,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CERILLO MAYA / CAJA CON 10 PAQUETES DE 50PZA',
                'category_id' => 17,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'AGUACATINA CHICA / CAJA CON 360PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'AGUACATINA GRANDE / CAJA CON 264PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'AGUACATINA MEDIANA / CAJA CON 252PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'ALCANFOR EN CUBOS / CAJA CON 32 TIRAS DE 20PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 28,
            ],
            [
                'name' => 'ALCOHOL AZUL-ROJO 115ML / PAQUETE CON 24PZA',
                'category_id' => 25,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'ALCOHOL AZUL Y ROJO 220ML / PAQUETE CON 24PZA',
                'category_id' => 25,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'ALKA-SELTZER / CAJA CON 20 EXHIBIDORES DE 100PZA',
                'category_id' => 25,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'ALUMINIO MEGA MAX #10 / CAJA CON 24PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'ALUMINIO MEGA MAX #50 / CAJA CON 12PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'ATUN DORADO EN ACEITE 140G / CHAROLA 24PZA',
                'category_id' => 3,
                'measure_unit_id' => 26,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'ATUN DORADO EN AGUA 140G / CHAROLA 24PZA',
                'category_id' => 3,
                'measure_unit_id' => 26,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'AZUCAR PORRES / 25KG',
                'category_id' => 9,
                'measure_unit_id' => 3,
                'retail_measure_unit_id' => 20,
            ],
            [
                'name' => 'AZUCAR SAN MIGUEL / 25KG',
                'category_id' => 9,
                'measure_unit_id' => 3,
                'retail_measure_unit_id' => 20,
            ],
            [
                'name' => 'BOLSA PARA BASURA 60X90 / BULTO CON 25 PAQUETES',
                'category_id' => 16,
                'measure_unit_id' => 3,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'BOLSA PARA BASURA 90X120 / BULTO CON 25 PAQUETES',
                'category_id' => 16,
                'measure_unit_id' => 3,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'CARILLERA / 40 PAQUETES DE 12PZA',
                'category_id' => 26,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'CINTA NAVITEC / PAQUETE CON 10 BOLSAS DE 50PZA',
                'category_id' => 16,
                'measure_unit_id' => 7,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'CINTA TRANPARENTE MAXI PLUS / 6PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'CINTA TRANPARENTE 150 METROS / 6PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'CORTA UÑAS DUREX / 50 EXHIBIDORES 12 PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'COUTURE UVA / 10 CAJETILLAS',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 2,
            ],
            [
                'name' => 'CURITA / 12 EXHIBIDORES CON 100PZA',
                'category_id' => 25,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'GLOBO PAYASO #7 / CAJA CON 50 BOLSAS DE 100PZA ',
                'category_id' => 26,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'GLOBO PIKOL #7 / CAJA CON 50 BOLSAS DE 100PZA ',
                'category_id' => 26,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'HULE PARA TIRADOR 20 METROS / 50 BOLSAS',
                'category_id' => 26,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'MICHE MIX ESPECIAL 240ML / 24PZA',
                'category_id' => 23,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'NAVAJAS DORCO / 10 EXHIBIDORES',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'PALILLOS TARRASQUITOS / 14 EXHIBIDORES CON 10 CAJETILLAS',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'PILAS PANASONIC AA / 12 EXHIBIDORES CON 12 TIRAS',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'PILAS PANASONIC AAA / 12 EXHIBIDORES CON 12 TIRAS',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'PILAS PANASONIC D / 12 EXHIBIDORES CON 24PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'MONY / 40 EXHIBIDORES 12PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'RAFIA DE COLORES 900G  / 16 ROLLOS',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 15,
            ],
            [
                'name' => 'RAIDOLITO RAID / 6 EXHIBIDORES CON 50PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'RASTRILLO BIC CONFORT / 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'RASTRILLO MAXIPLUS AZUL / 10PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'RASTRILLO MAXIPLUS AMARILLO / 10PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'RASTRILLO DORCO AMARILLO Y AZUL / CAJA CON 12 EXHIBIDORES DE 12 BOLSAS DE 10 PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'RASTRILLO PERMA SHARP DE 1RA / TIRA 24PZA',
                'category_id' => 12,
                'measure_unit_id' => 28,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'RASTRILLO PERMA SHARP DE 2DA / TIRA 24PZA',
                'category_id' => 12,
                'measure_unit_id' => 28,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'SAL CISNE 1KG / 20 BOLSAS',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'SAL FINA 1KG / 20 BOLSAS',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'SAL PALOMITO 50KG / ',
                'category_id' => 9,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 14,
            ],
            [
                'name' => 'SAL DE UVAS PICOT  / CAJA CON 50 EXHIBIDORES DE 50 PZA',
                'category_id' => 25,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'SHAMPOO CAPRIS ANTI CASPA 190ML / 15PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'SHAMPOO CAPRIS CERAMIDA 190ML / 15PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'SHAMPOO CAPRIS HERBAL 190ML / 15PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'SHAMPOO CAPRIS CONTROL CAIDA 190ML / 15PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'SHAMPOO PANTENE 100ML / 8 PAQUETES 6 PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'SHAMPOO HEAD SHOULDERS 90ML / 8 PAQUETES 6 PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'SHAMPOO HEAD SHOULDERS 180ML / 8 PAQUETES 6 PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'SHAMPOO HEAD SHOULDERS 375ML / 8 PAQUETES 6 PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 7,
            ],
            [
                'name' => 'SHAMPOO HEAD SHOULDERS 1LT / 9 BOTELLAS',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'SHAMPOO HEAD SHOULDERS 90ML / 24 BOTELLAS',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 9,
            ],
            [
                'name' => 'SUPER GLUE / 25 TIRAS DE 12PZA',
                'category_id' => 22,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 28,
            ],
            [
                'name' => 'TOKI SURTIDO / CAJA CON 25 TIRAS DE 24 SOBRES',
                'category_id' => 23,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 28,
            ],
            [
                'name' => 'TROPI SURTIDO / CAJA CON 24 TIRAS DE 12 SOBRES',
                'category_id' => 23,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 28,
            ],
            [
                'name' => 'VAPE ESPIRAL / 12 EXHIBIDORES 50PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'VELADORA LIMONERO PARAFINA / 20PZA',
                'category_id' => 16,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'VICK VAPORUB DE 1ERA / 30 EXHIBIDORES DE 12 LATAS',
                'category_id' => 25,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'VICK VAPORUB DE 2DA / 30 EXHIBIDORES DE 12 LATAS',
                'category_id' => 25,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 4,
            ],
            [
                'name' => 'GEL EGO MAGNETIN 200ML / 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'GEL EGO ATRACCION 200ML / 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'GEL EGO ALFA 200ML / 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
            [
                'name' => 'GEL XTREME 200ML / 12PZA',
                'category_id' => 12,
                'measure_unit_id' => 1,
                'retail_measure_unit_id' => 6,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
